name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2016
    
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.
    
    - run: dotnet publish -r win-x64 -c release

    - run: dir /S

    - uses: actions/upload-artifact@master
      with:
        name: concerto-win64
        path: bin/release/netcoreapp3.0/win-x64/native
